# Generated by Django 3.2.6 on 2021-08-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixpeople', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['time_create', 'content'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чат'},
        ),
        migrations.AlterField(
            model_name='people',
            name='content',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='people',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='people',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последние изменение'),
        ),
    ]
